name: 'CICD Integration'
on:
  push:
    branches:
    - "main"
    - "dev"
    - "qa"
defaults:
  run:
    shell: bash
jobs:
  CICD:
    name: 'CICD'
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Run script file Prod
      if: github.ref != 'refs/heads/main'
      run: |
        echo "Ejecucion CICD Integration Prod"
      shell: bash