name: 'CICD Integration'
on:
  push:
    branches:
    - "main"
defaults:
  run:
    shell: bash
jobs:
  CICD:
    name: 'CICD'
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Run script file
      run: |
        echo "Ejecucion CICD Integration"
      shell: bash