name: 'CICD Integration'
on:
  push:
    branches:
    - "main"
defaults:
  run:
    shell: bash
jobs:
  CICD:
    name: 'CICD'
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Run script file
      if: github.ref == 'refs/heads/qa'
      run: |
        echo "Ejecucion CICD Integration QA"
      shell: bash
    - name: Run script file
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "Ejecucion CICD Integration Dev"
      shell: bash
    - name: Run script file
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Ejecucion CICD Integration Prod"
      shell: bash